EJERCICIOS PROPUESTO 4.1

CREATE TABLE PROFESOR(
DNI VARCHAR(9) NOT NULL,
NOMBRE VARCHAR(41) NOT NULL,
AP1 VARCHAR(35) NOT NULL,
AP2 VARCHAR(35) NULL,
DIRECCION VARCHAR(40) NOT NULL,
CUENTA NUMBER(20) NOT NULL,
TELEFONO NUMBER(9) NOT NULL,
CONSTRAINT PK_DNI_PROFESOR PRIMARY KEY(DNI)
);

CREATE TABLE CICLOFORM(
CODCICLO NUMBER(4) NOT NULL,
NOMBRE VARCHAR(41) NOT NULL,
TIPO VARCHAR(30) NOT NULL,
CONSTRAINT PK_CODCICLO_CICLOFORM PRIMARY KEY(CODCICLO)
);

CREATE TABLE ASIGNATURA(
CODASIG NUMBER(4) NOT NULL,
NOMBRE VARCHAR(41) NOT NULL,
NUMHORAS NUMBER(2) NOT NULL,
DNI_PROFESOR NUMBER(9) NOT NULL,
CONSTRAINT PK_CODASIG_ASIGNATURA PRIMARY KEY(CODASIG),
CONSTRAINT FK_DNI FOREIGN KEY(DNI_PROFESOR) REFERENCES PROFESOR(DNI)
);

CREATE TABLE IDIOMA(
CODIDIOMA NUMBER(4) NOT NULL,
DESCRIPCION VARCHAR(40) NOT NULL,
CONSTRAINT PK_CODIDIOMA PRIMARY KEY(CODIDIOMA)
);

CREATE TABLE ALUMNO(
DNI VARCHAR(9) NOT NULL,
NOMBRE VARCHAR(41) NOT NULL,
AP1 VARCHAR(35) NOT NULL,
AP2 VARCHAR(35) NULL,
DIRECCION VARCHAR(20) NOT NULL,
EMAIL VARCHAR(20) NOT NULL,
TELEFONO VARCHAR(9) NOT NULL,
CONSTRAINT PK_DNI_ALUMNO PRIMARY KEY(DNI),
CONSTRAINT FK_CODIDIOMA FOREIGN KEY(CODIDIOMA) REFERENCES IDIOMA(CODIDIOMA)
);

CREATE TABLE MATRICULA(
DNI VARCHAR(9) NOT NULL,
CODASIG NUMBER(4) NOT NULL,
CONSTRAINT PK_DNI_CODASIG PRIMARY KEY(DNI, CODASIG),
CONSTRAINT PF_DNI_CODASIG FOREIGN KEY(DNI, CODASIG)
);

CREATE TABLE IDIOMASPROF(
CODIDIOMA NUMBER(4) NOT NULL,
DNI NUMBER(9) NOT NULL,
CONSTRAINT PK_DNI_CODIDIOMA PRIMARY KEY(DNI, CODIDIOMA),
CONSTRAINT FK_PROFESOR FOREIGN KEY(DNI) REFERENCES PROFESOR(DNI),
CONSTRAINT FK_IDIOMA FOREIGN KEY(CODIDIOMA) REFERENCES IDIOMA(CODIDIOMA)
);